baseurl = "/"
title = "Ben Anderson"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "&copy; 2018 Benjamin Anderson"
disqusShortname = ""
googleAnalytics = ""
enableEmoji = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "Ben Anderson"
    profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Ben Anderson"
    description = "Mistakes Were Made"
    github = "https://github.com/benande"
#    gitlab = "https://gitlab.com/XXX"
    linkedin = "https://www.linkedin.com/in/benjamin-anderson-52694b7/"
#    gplus = "https://google.com/+XXX"
    twitter = "https://twitter.com/BenIsTinkering"
#    stackoverflow = "https://stackoverflow.com/users/XXX/YYY"
    email = "benande@gmail.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4
